### ISSUE TITLE
Should you use documentation or enhancement label when modifying or adding a guide?

### ISSUE THREAD

**Issue by wkrzos** [Solvro/web-solvro-docs#23]
When creating a pull request in which you add or modify a guide, should you label it as enhancement or documentation? Cheers!

**Comment by wkrzos** [comment]
Would love to get your opinion on it @Rei-x

**Comment by Rei-x** [comment]
> When creating a pull request in which you add or modify a guide, should you label it as enhancement or documentation? Cheers!

nie używamy labelek
